redundancy = 2

[host]
id = 1
uri = "tcp://localhost:1881"

[[neighbors]]
id = 0
uri = "tcp://localhost:1880"

[[neighbors]]
id = 3
uri = "tcp://localhost:1883"

[[neighbors]]
id = 4
uri = "tcp://localhost:1884"
