redundancy = 2

[host]
id = 3
ip = "127.0.0.1"
port = 1883

[[neighbors]]
id = 2
ip = "127.0.0.1"
port = 1882

[[neighbors]]
id = 5
ip = "127.0.0.1"
port = 1885

[[neighbors]]
id = 4
ip = "127.0.0.1"
port = 1884

[[neighbors]]
id = 1
ip = "127.0.0.1"
port = 1881
