redundancy = 2
cache_size = 500

[host]
id = 6
ip = "127.0.0.1"
port = 1886

[[neighbors]]
id = 3
ip = "127.0.0.1"
port = 1883

[[neighbors]]
id = 5
ip = "127.0.0.1"
port = 1885

[[neighbors]]
id = 9
ip = "127.0.0.1"
port = 1889



